### PR TITLE
fix anchor scroll

### LINKED ISSUE #104: Linking to an anchor doesn't scroll
eg. https://next.vuetifyjs.com/components/lists#api should scroll to the API section when the page loads

### PR DESCRIPTION
**Pull request by jmarcelo93**
fixes #104

### CODE REVIEW

File: assets/App.vue [hunk 1]
```diff
@@ -90,4 +90,14 @@
 
   .dashme
     border: 1px dashed black !important
+
+  main
+    section
+        &:before
```
Comment (johnleider) [inline assets/App.vue]: this looks like it is using tabs or 4 spaces, can you convert to 2
