### PR TITLE
fixed crud example

### LINKED ISSUE #229: CRUD example saves the data event if "Save" button is not clicked
https://next.vuetifyjs.com/components/data-tables#example-crud

Open edit dialog, change some data, press "Close" - data in the table does not revert to the original value
Maybe this could be solved with `return-value.sync` prop of `v-dialog`

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
fixes #229

added confirm on delete
editing item and closing without saving doesn't change the item in table

### CODE REVIEW

File: examples/data-tables/crud.vue [hunk 1]
```diff
@@ -183,13 +183,14 @@
         ]
       },
 
-      editItem (index) {
-        this.editedIndex = index
-        this.editedItem = Object.assign({}, this.items[index])
+      editItem (item) {
+        this.editedIndex = this.items.findIndex(i => i === item)
```
Comment (KaelWD) [inline examples/data-tables/crud.vue]: Why not `indexOf`?

Comment (KaelWD) [reply examples/data-tables/crud.vue]: Actually, `editedIndex` doesn't even need to exist. It looks like it's just used to determine if it's a new item or not, so it could be replaced with a boolean.

File: examples/data-tables/crud.vue [hunk 2]
```diff
@@ -187,29 +184,29 @@
...
-        this.items.splice(index, 1)
+      deleteItem (item) {
+        const index = this.items.findIndex(i => i === item)
+        confirm('Are you sure you want to delete this item?') && this.items.splice(index, 1)
       },
 
       close () {
-        this.item.edit = false
+        this.editedItem = Object.assign({}, this.defaultItem)
+        this.editedIndex = -1
```
Comment (KaelWD) [inline examples/data-tables/crud.vue]: This should be done after a 300ms timeout to ensure the dialog animation has finished.

File: examples/data-tables/crud.vue (hunk 1 above)
Comment (jacekkarczmarczyk) [reply examples/data-tables/crud.vue]: I need to update the item in items after saving. Dialog gets the item's copy
